- name: Go (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - golang.go
        - premparihar.gotestexplorer
        - maxmedia.go-prof
