- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    docker_distribution: "{{ 'ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution | lower }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    machine_arch: "{{ 'Darwin-x86_64' if is_mac else 'Linux-x86_64' }}"

  tasks:
    # Linux

    - name: Install Docker pre-requisites
      become: yes
      apt:
        package: gnupg-agent
      when: not is_mac

    - name: Determine Docker Compose latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep \"browser_download_url.*Linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_compose_version
      when: not is_mac

    - name: Install Docker Compose (Linux)
      become: yes
      get_url:
        url: "{{ docker_compose_version.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: 0755
      when: not is_mac

    - name: Add Docker APT package key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/{{ docker_distribution }}/gpg
      when: not is_mac

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ docker_distribution }} {{ ansible_distribution_release }} stable
        filename: docker
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Docker engine (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
      when: not is_mac

    - name: Enable Docker engine for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes
      when: not is_mac

    # macOS

    - name: Install Docker Compose (macOS)
      homebrew:
        name: docker-compose
      when: is_mac

    - name: Install Docker engine (macOS)
      homebrew_cask:
        name: docker
      when: is_mac

    # Common

    - name: Determine Docker Machine latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/machine/releases/latest | grep \"browser_download_url.*{{ machine_arch }}\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_machine_version

    - name: Install Docker Machine
      become: yes
      get_url:
        url: "{{ docker_machine_version.stdout }}"
        dest: /usr/local/bin/docker-machine
        mode: 0755
