- name: Virtualization
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Test for hypervisor (Linux)
      shell: dmesg | grep -i "hypervisor detected" || true
      register: hypervisor
      when: not is_mac and not is_wsl

    - name: Install QEMU/KVM (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - bridge-utils
        - libvirt-clients
        - libvirt-daemon-system
        - ovmf
        - qemu-kvm
        - virt-manager
      when: not is_mac and not is_wsl and hypervisor.stdout == ""

    - name: Enable QEMU/KVM for current user (Linux)
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=libvirt
        append=yes
      when: not is_mac and not is_wsl and hypervisor.stdout == ""

    # macOS

    - name: Install VirtualBox (macOS)
      homebrew_cask:
        name: virtualbox
      when: is_mac
