- name: Uninstall Microsoft Edge
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Uninstall Microsoft Edge"
      become: yes
      apt:
        package: microsoft-edge-stable
        state: absent
        purge: yes
      when: not is_wsl

    - name: "[Non-WSL] Remove Microsoft APT package repository"
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge/ stable main
        filename: microsoft-edge
        state: absent
      when: not is_wsl

    - name: "[Non-WSL] Remove Microsoft APT package key"
      become: yes
      file:
        path: /etc/apt/trusted.gpg.d/microsoft.asc
        state: absent
      when: not is_wsl
