- name: Mono
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    mono_distribution: "{{ 'ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution | lower }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add Mono APT package key
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      when: not is_mac

    - name: Add Mono APT package repository
      become: yes
      apt_repository:
        repo: deb https://download.mono-project.com/repo/{{ mono_distribution }} stable-{{ ansible_distribution_release }} main
        filename: mono-official-stable
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Mono (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - mono-complete
        - mono-vbnc
      register: mono_install
      when: not is_mac

    - name: Disable .NET app auto-run with Mono (WSL)
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Disable Mono auto-run for Windows apps (WSL)"
        block: |
          sudo update-binfmts --disable cli
      when: is_wsl

    # macOS

    - name: Install Mono (macOS)
      homebrew:
        name: mono
      when: is_mac
